

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adorno-backend-part1
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env          
    restart: unless-stopped
    networks:
      - adorno-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adorno-frontend-part1
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - adorno-network

networks:
  adorno-network:
    driver: bridge